"""
Mock provider 测试模块。

验证图片和视频 mock provider 输出符合预期：
- URL 使用 mock:// 协议
- metadata 包含 provider/is_mock/note
- 视频 progress 设置为 100
@author ganjianfei
@version 1.0.0
2026-06-12
"""

import pytest

from src.agents.image_generator import ImageGeneratorAgent, generate_product_image
from src.agents.video_generator import VideoGeneratorAgent
from src.graph.state import AgentState
from src.models.assets import AssetStatus
from src.models.storyboard import Scene, SceneType, ShotType, Storyboard


def _make_storyboard() -> Storyboard:
    """构建测试用 Storyboard。"""
    scene = Scene(
        scene_id=1,
        scene_type=SceneType.PRODUCT_INTRO,
        duration=5.0,
        shot_type=ShotType.MEDIUM,
        description="产品正面展示",
        visual_prompt="Product hero shot",
    )
    return Storyboard(
        storyboard_id="sb_test",
        title="测试分镜",
        description="测试用分镜脚本",
        total_duration=5.0,
        resolution="1080p",
        visual_style="科技感",
        scenes=[scene],
    )


def _make_state(storyboard: Storyboard) -> AgentState:
    """构建测试用 AgentState。"""
    return AgentState(
        generation_prompts=[
            {
                "prompt": "A beautiful product photo",
                "image_type": "main",
                "style_keywords": ["studio lighting"],
                "aspect_ratio": "1:1",
            }
        ],
        storyboard=storyboard,
    )


class TestMockImageProvider:
    """图片 mock provider 测试。"""

    @pytest.mark.asyncio
    async def test_image_url_uses_mock_scheme(self) -> None:
        """图片 URL 应使用 mock://images/... 格式。"""
        agent = ImageGeneratorAgent()
        storyboard = _make_storyboard()
        state = _make_state(storyboard)

        result = await agent.execute(state)

        assert result.success is True
        images = result.data["generated_images"]
        assert len(images) > 0
        for img_data in images:
            url = img_data["url"]
            assert url is not None
            assert url.startswith("mock://images/"), f"Expected mock://images/..., got {url}"
            assert "example.com" not in url, f"URL should not contain example.com: {url}"

    @pytest.mark.asyncio
    async def test_image_metadata_has_mock_markers(self) -> None:
        """图片 metadata 应包含 provider/is_mock/note。"""
        agent = ImageGeneratorAgent()
        storyboard = _make_storyboard()
        state = _make_state(storyboard)

        result = await agent.execute(state)

        assert result.success is True
        images = result.data["generated_images"]
        for img_data in images:
            metadata = img_data.get("metadata", {})
            assert metadata.get("provider") == "mock"
            assert metadata.get("is_mock") is True
            assert "Placeholder asset generated by mock provider" in metadata.get("note", "")

    @pytest.mark.asyncio
    async def test_generate_product_image_tool_mock_url(self) -> None:
        """工具函数也应返回 mock:// 格式的 URL。"""
        result = await generate_product_image.ainvoke(
            {"prompt": "test", "style": "realistic", "aspect_ratio": "1:1", "num_images": 1}
        )
        assert result["success"] is True
        for img in result["images"]:
            assert img["url"].startswith("mock://images/")
            assert "example.com" not in img["url"]


class TestMockVideoProvider:
    """视频 mock provider 测试。"""

    @pytest.mark.asyncio
    async def test_video_url_uses_mock_scheme(self) -> None:
        """视频 URL 应使用 mock://videos/... 格式。"""
        agent = VideoGeneratorAgent()
        storyboard = _make_storyboard()
        state = _make_state(storyboard)

        result = await agent.execute(state)

        assert result.success is True
        video_data = result.data["generated_video"]
        url = video_data["url"]
        assert url is not None
        assert url.startswith("mock://videos/"), f"Expected mock://videos/..., got {url}"
        assert "example.com" not in url, f"URL should not contain example.com: {url}"

    @pytest.mark.asyncio
    async def test_video_metadata_has_mock_markers(self) -> None:
        """视频 metadata 应包含 provider/is_mock/note。"""
        agent = VideoGeneratorAgent()
        storyboard = _make_storyboard()
        state = _make_state(storyboard)

        result = await agent.execute(state)

        assert result.success is True
        video_data = result.data["generated_video"]
        metadata = video_data.get("metadata", {})
        assert metadata.get("provider") == "mock"
        assert metadata.get("is_mock") is True
        assert "Placeholder asset generated by mock provider" in metadata.get("note", "")

    @pytest.mark.asyncio
    async def test_video_progress_is_100(self) -> None:
        """视频 mock provider 进度应设置为 100。"""
        agent = VideoGeneratorAgent()
        storyboard = _make_storyboard()
        state = _make_state(storyboard)

        result = await agent.execute(state)

        assert result.success is True
        video_data = result.data["generated_video"]
        assert video_data["progress"] == 100.0, f"Expected progress 100, got {video_data['progress']}"

    @pytest.mark.asyncio
    async def test_video_status_is_completed(self) -> None:
        """视频 mock provider 状态应为 completed。"""
        agent = VideoGeneratorAgent()
        storyboard = _make_storyboard()
        state = _make_state(storyboard)

        result = await agent.execute(state)

        assert result.success is True
        video_data = result.data["generated_video"]
        assert video_data["status"] == AssetStatus.COMPLETED.value
